# Generated by Django 6.0.7 on 2026-07-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AlterModelOptions(
            name='otp',
            options={'verbose_name': 'OTP', 'verbose_name_plural': 'OTPs'},
        ),
    ]
