# Generated by Django 6.0.7 on 2026-07-16 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workinghours',
            options={'ordering': ['weekday', 'start_time'], 'verbose_name_plural': 'Working Hours'},
        ),
    ]
